onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/clk_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/rst_ni}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/req_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/we_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/addr_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/wdata_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/be_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/rdata_o}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/r_addr_q}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/rdata_q}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/rdata_d}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/sram}
add wave -noupdate -divider {amo wrapper}
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/clk_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/rst_ni
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_addr_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_prot_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_region_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_atop_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_len_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_size_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_burst_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_lock_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_cache_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_qos_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_id_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_user_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_ready_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_valid_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_addr_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_prot_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_region_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_len_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_size_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_burst_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_lock_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_cache_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_qos_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_id_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_user_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_ready_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_valid_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_w_data_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_w_strb_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_w_user_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_w_last_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_w_ready_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_w_valid_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_r_data_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_r_resp_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_r_last_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_r_id_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_r_user_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_r_ready_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_r_valid_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_b_resp_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_b_id_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_b_user_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_b_ready_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_b_valid_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_addr_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_prot_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_region_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_atop_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_len_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_size_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_burst_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_lock_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_cache_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_qos_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_id_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_user_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_ready_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_valid_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_addr_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_prot_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_region_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_len_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_size_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_burst_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_lock_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_cache_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_qos_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_id_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_user_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_ready_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_valid_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_w_data_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_w_strb_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_w_user_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_w_last_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_w_ready_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_w_valid_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_r_data_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_r_resp_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_r_last_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_r_id_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_r_user_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_r_ready_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_r_valid_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_b_resp_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_b_id_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_b_user_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_b_ready_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_b_valid_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_check_id
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_set_id
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_id_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_id_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_check_addr
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_clr_addr
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_set_addr
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/rd_clr_addr
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/wr_clr_addr
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_addr_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_addr_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_check_req
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_check_gnt
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_clr_req
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_clr_gnt
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_set_req
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_set_gnt
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/rd_clr_req
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/rd_clr_gnt
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/wr_clr_req
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/wr_clr_gnt
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/art_check_res
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/b_excl_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/b_excl_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/r_excl_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/r_excl_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/r_state_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/r_state_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_state_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_state_q
add wave -noupdate -divider {non so}
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/clk_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/rst_ni
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/clr_addr_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/clr_req_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/clr_gnt_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/set_addr_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/set_id_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/set_req_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/set_gnt_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/check_addr_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/check_id_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/check_res_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/check_req_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/check_gnt_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/tbl_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/tbl_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/clr
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/i_art/set
add wave -noupdate -divider Focus
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_state_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_w_strb_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/wr_clr_addr
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_addr_d
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/w_addr_q
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_addr_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_aw_lock_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/slv_ar_lock_i
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_aw_lock_o
add wave -noupdate /ariane_tb/dut/i_axi_riscv_atomics/i_atomics/i_lrsc/mst_ar_lock_o
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/sram[30007]}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/sram[13771]}
add wave -noupdate -divider DRAM
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/sram[8003]}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/sram[13354]}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/req_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/we_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/addr_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/wdata_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/be_i}
add wave -noupdate {/ariane_tb/dut/i_sram/gen_cut[0]/gen_mem/i_tc_sram_wrapper/i_tc_sram/rdata_o}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1888757 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {1888487 ns} {1888813 ns}
